### PR TITLE
Remove clip groups from the SVG file

### PR DESCRIPTION
**Pull request by MacKenzieRose**
Hoping this will resolve the intermittent issues where the SVG doesn't go all the way to the edge of its container width

### CODE REVIEW

**Review by JessJodoin — APPROVED** [review]
😍

**Comment by JessJodoin** [comment]
I'm stuck at a weird place where it won't let me merge and it's yellow saying it's checking ability to merge automatically :( 

I dunno what to do, maybe I'll try again tomorrow?

**Comment by JessJodoin** [comment]
I'm stuck at a weird place where it won't let me merge and it's yellow saying it's checking ability to merge automatically :( 

I dunno what to do, maybe I'll try again tomorrow?

**Comment by MacKenzieRose** [comment]
Weirdly enough, I think it will let me merge my own pull request? RIDICULOUS

**Pull request merged**
